#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

use Conso\Input;
use Conso\Output;
use OoFile\Conf;
use App\Kernel\Http;

require 'vendor/autoload.php';

$webKernel = new Http; // should be replaced with consol kernel

$webKernel->enableErrorHandler();
$webKernel->loadConfig();
$webKernel->loadWebRoutes();


$app = new Conso\App(new Input, new Output);

Conf::append("app","COMMANDS", array(
    __DIR__ . '/vendor/lotfio/aven/src/Aven/Console/Commands',
    __DIR__ . '/app/Console/Commands',
));

Conf::append("app","NAMESPACE", array(
    "Aven\\Console\\Commands\\",
    "App\\Console\\Commands\\",
));
// start application
$app->run();