#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

use Conso\Input;
use Conso\Output;
use App\Console\Kernel;

require 'vendor/autoload.php';

/**
 * load kernel
 */
$consoleKernel = new Kernel;

/**
 * enable ouch
 */
$consoleKernel->enableErrorHandler();

/**
 * load config 
 */
$consoleKernel->loadConfig();

/**
 * load routes for aven
 */
$consoleKernel->loadWebRoutes();

/**
 * bind input and output to app
 */
$app = new Conso\App(new Input, new Output);

/**
 * start silo console application
 */
$app->run();