#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 *
 * @author    <contact@lotfio.net>
 * @package   Conso PHP Console Creator
 * @version   0.1.0
 * @license   MIT
 * @category  CLI
 * @copyright 2019 Lotfio Lakehal
 */

use Conso\Input;
use Conso\Output;

/**
 * autoloader 
 */
require 'vendor/autoload.php';

/**
 * get application assistant
 */
require 'app/assistant.php';

/**
 * bind input and output to app
 */
$app = new Conso\App(new Input, new Output);

/**
 * start silo console application
 */
$app->run();